package config

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"
)

type Config struct {
	AppEnv   string
	Domain   string
	APIPort  string
	LogLevel string

	// AllowedOrigins is the list of origins permitted by the CORS middleware.
	// Populated from the ALLOWED_ORIGINS env var (comma-separated).
	AllowedOrigins []string

	// TrustedProxyCIDRs is the list of CIDR subnets whose X-Real-IP header
	// should be trusted by the rate limiter. Comma-separated, e.g. "10.0.0.0/8".
	TrustedProxyCIDRs []string

	// Database
	Postgres PostgresConfig

	// Redis
	Redis RedisConfig

	// MinIO
	MinIO MinIOConfig

	// JWT
	JWT JWTConfig

	// Security
	BcryptCost     int
	MaxUploadSize  int64
	RateLimitRPS   int
	RateLimitBurst int

	// LiveKit (WebRTC media server)
	LiveKitAPIKey     string
	LiveKitAPISecret  string
	LiveKitWSURL      string // Browser-facing URL returned to frontend (ws://127.0.0.1:7880)
	LiveKitTURNSecret string // Shared secret for generating ephemeral TURN credentials
}

type PostgresConfig struct {
	Host     string
	Port     string
	User     string
	Password string
	DB       string
	SSLMode  string
}

func (p PostgresConfig) DSN() string {
	return fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=%s",
		p.User, p.Password, p.Host, p.Port, p.DB, p.SSLMode)
}

type RedisConfig struct {
	Host     string
	Port     string
	Password string
}

func (r RedisConfig) Addr() string {
	return fmt.Sprintf("%s:%s", r.Host, r.Port)
}

type MinIOConfig struct {
	Endpoint  string
	AccessKey string
	SecretKey string
	Bucket    string
	UseSSL    bool
	PublicURL string // Base public URL for constructed file URLs (e.g. https://cdn.example.com)
}

type JWTConfig struct {
	Secret        string
	AccessExpiry  time.Duration
	RefreshExpiry time.Duration
}

func Load() (*Config, error) {
	// C2: Fatal at startup if JWT_SECRET is empty — prevents trivially forgeable tokens.
	jwtSecret, jwtSet := lookupEnv("JWT_SECRET")
	if !jwtSet || jwtSecret == "" {
		log.Fatal("JWT_SECRET environment variable must be set and non-empty")
	}

	// H6: LIVEKIT_TURN_SECRET is optional — if unset, ephemeral TURN credentials
	// will not be generated by the ICE handler.
	turnSecret := getEnv("LIVEKIT_TURN_SECRET", "")

	accessExpiry, err := time.ParseDuration(getEnv("JWT_ACCESS_EXPIRY", "15m"))
	if err != nil {
		return nil, fmt.Errorf("invalid JWT_ACCESS_EXPIRY: %w", err)
	}

	refreshExpiry, err := time.ParseDuration(getEnv("JWT_REFRESH_EXPIRY", "168h"))
	if err != nil {
		return nil, fmt.Errorf("invalid JWT_REFRESH_EXPIRY: %w", err)
	}

	bcryptCost, err := strconv.Atoi(getEnv("BCRYPT_COST", "12"))
	if err != nil {
		return nil, fmt.Errorf("invalid BCRYPT_COST: %w", err)
	}

	maxUpload, err := strconv.ParseInt(getEnv("MAX_UPLOAD_SIZE", "52428800"), 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid MAX_UPLOAD_SIZE: %w", err)
	}

	rps, err := strconv.Atoi(getEnv("RATE_LIMIT_RPS", "60"))
	if err != nil {
		return nil, fmt.Errorf("invalid RATE_LIMIT_RPS: %w", err)
	}

	burst, err := strconv.Atoi(getEnv("RATE_LIMIT_BURST", "120"))
	if err != nil {
		return nil, fmt.Errorf("invalid RATE_LIMIT_BURST: %w", err)
	}

	useSSL := getEnv("MINIO_USE_SSL", "false") == "true"

	// H1: configurable SSL mode for PostgreSQL.
	// Default is "disable" because the stock postgres Docker image ships without
	// TLS certificates.  Set POSTGRES_SSLMODE=require (or verify-full) when
	// connecting to a managed / production database that has TLS enabled.
	sslMode := getEnv("POSTGRES_SSLMODE", "disable")

	// Parse comma-separated lists
	allowedOrigins := splitCSV(getEnv("ALLOWED_ORIGINS", ""))
	trustedProxies := splitCSV(getEnv("TRUSTED_PROXY_CIDRS", ""))

	domain := getEnv("DOMAIN", "localhost")

	return &Config{
		AppEnv:            getEnv("APP_ENV", "production"),
		Domain:            domain,
		APIPort:           getEnv("API_PORT", "8080"),
		LogLevel:          getEnv("API_LOG_LEVEL", "info"),
		AllowedOrigins:    allowedOrigins,
		TrustedProxyCIDRs: trustedProxies,
		Postgres: PostgresConfig{
			Host:     getEnv("POSTGRES_HOST", "localhost"),
			Port:     getEnv("POSTGRES_PORT", "5432"),
			User:     getEnv("POSTGRES_USER", "pulse"),
			Password: getEnv("POSTGRES_PASSWORD", ""),
			DB:       getEnv("POSTGRES_DB", "pulse"),
			SSLMode:  sslMode,
		},
		Redis: RedisConfig{
			Host:     getEnv("REDIS_HOST", "localhost"),
			Port:     getEnv("REDIS_PORT", "6379"),
			Password: getEnv("REDIS_PASSWORD", ""),
		},
		MinIO: MinIOConfig{
			Endpoint:  getEnv("MINIO_ENDPOINT", "localhost:9000"),
			AccessKey: getEnv("MINIO_ROOT_USER", ""),
			SecretKey: getEnv("MINIO_ROOT_PASSWORD", ""),
			Bucket:    getEnv("MINIO_BUCKET", "pulse-uploads"),
			UseSSL:    useSSL,
			PublicURL: getEnv("MINIO_PUBLIC_URL", ""), // e.g. https://cdn.example.com
		},
		JWT: JWTConfig{
			Secret:        jwtSecret,
			AccessExpiry:  accessExpiry,
			RefreshExpiry: refreshExpiry,
		},
		BcryptCost:        bcryptCost,
		MaxUploadSize:     maxUpload,
		RateLimitRPS:      rps,
		RateLimitBurst:    burst,
		LiveKitAPIKey:     getEnv("LIVEKIT_API_KEY", "devkey"),
		LiveKitAPISecret:  getEnv("LIVEKIT_API_SECRET", ""),
		LiveKitWSURL:      getEnv("LIVEKIT_WS_URL", "ws://127.0.0.1:7880"),
		LiveKitTURNSecret: turnSecret,
	}, nil
}

// lookupEnv returns the value and whether it was explicitly set.
// L4 fix: distinguish "not set" from "set to empty string".
func lookupEnv(key string) (string, bool) {
	return os.LookupEnv(key)
}

// getEnv returns the env value or the fallback. If the variable is explicitly
// set to an empty string the fallback is NOT used — the empty string is the
// caller's intended value. This is consistent with the L4 fix for the guard
// in Load() above.
func getEnv(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}

// splitCSV splits a comma-separated string into a trimmed, non-empty slice.
// Uses standard library strings.Split and strings.TrimSpace.
func splitCSV(s string) []string {
	if s == "" {
		return nil
	}
	var result []string
	for _, part := range strings.Split(s, ",") {
		if t := strings.TrimSpace(part); t != "" {
			result = append(result, t)
		}
	}
	return result
}
